Ioan cosarca task 1
IoanCosarca/Bistro-Application pull request #1
Opened 2023-08-11 12:08 UTC by IoanCosarca

Pull request for code review

2023-08-11 17:03 UTC, andrutza commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=true
What is this property used for?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +            System.out.println("-------------List Products---------------");
Can you please move everything that in related to console to a separate file and package?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +            System.out.println("-------------Remove Product by ID---------------");
Please move each action/operation to a separate method.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +    private static Ingredient findIngredient(IngredientType ingredientType,
Please move the find methods to the service layer.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +            System.out.println(customer.toString());
Please move all the prints to the console layer.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +    public Set<Customer> returnCustomers() {
Can you please rename this method?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/OrderController.java
> +    public Set<Product> getTop3() {
Can you please rename this method and maybe have a property for the number 3, as this can be changed in the future, for example to get most 5 wanted products.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +                    Arrays.toString(Arrays.stream(e.getStackTrace()).map(s -> s + "\n").toArray()));
Usually, it is not needed to do so complicated logic to print an exception, it should be enough to log/print in this case "e".

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/Ingredient.java
> +    private Double cost;
I would have used BigDecimal for cost field.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/IngredientType.java
> +    FLOUR,
Can you please also use a field name for the enum to be more clearly especially when you want to show the ingredient type (example: tomato_sauce should be shown as tomate sauce)?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/PlacedOrder.java
> +    private Double totalPrice = 0.0;
Same as above.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/PlacedOrder.java
> +    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
Do you want to use eager for each type of relationship?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/PlacedOrder.java
> +            this.totalPrice += p.getProduct().getPrice();
Can you please move this logic to the service layer?

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/Product.java
> +        for (Ingredient ingredient : ingredients) {
Same as above.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/repository/CustomerSeeder.java
> +    private Set<Customer> getCustomers()
I think a better name of this method would be populateCustomers().

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/repository/IngredientSeeder.java
> +    private Set<Ingredient> getIngredients()
Same as above.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/repository/ProductSeeder.java
> +    private List<Product> getProducts()
Same as above.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/OrderService.java
> +    Set<Product> getTop3();
This method should be defined more generic: for example getMostWantedProducts(int n).

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/OrderServiceImpl.java
> +        for (PlacedOrder placedOrder : customerOrders) {
I would change this to use stream and filter instead of foreach and if.

2023-08-11 17:03 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/ProductServiceImpl.java
> +        if (productOptional.isEmpty()) {
I would use directly here the method ifPresentOrElse().

2023-08-14 08:20 UTC, IoanCosarca commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +                    Arrays.toString(Arrays.stream(e.getStackTrace()).map(s -> s + "\n").toArray()));
I explained this part a bit when I presented my code.
If I leave it to e.getStackTrace(), I only get this:
![image](https://github.com/IoanCosarca/Bistro-Application/assets/123205755/b93a4e02-6487-4297-962c-7b0a5a4d7f90)

And if I do Arrays.toString(e.getStackTrace()), I get this:
![image](https://github.com/IoanCosarca/Bistro-Application/assets/123205755/16c2bf17-f5a1-4c0e-b3d0-2af5fa89cc62)
Just one link, and it's very hard to understand. Personally, I don't think this helps anyone in debugging.

But if I leave it with the formatting I made, the output is the following:
![image](https://github.com/IoanCosarca/Bistro-Application/assets/123205755/220b32fb-d708-45bc-bcac-77e9c6ab9241)
It has links to the entire stack, every stack element is shown on a separate line and it's very easy to read and understand the stack process.

2023-08-14 10:16 UTC, IoanCosarca commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=true
That is a default Spring feature. It manages the Hibernate Session. By default, when you start a Spring Application it is set to true. However, if you don't explicitly configure it, it just gives a small warning when you initialize Spring Boot.
![image](https://github.com/IoanCosarca/Bistro-Application/assets/123205755/1c436c55-96a8-474a-b47c-2731cd19f11e)

That is the only reason why I configured it, to get rid of that warning.

2023-08-16 15:06 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +                    Arrays.toString(Arrays.stream(e.getStackTrace()).map(s -> s + "\n").toArray()));
You can leave it for this scenario also, but please don't use it in this way in the future.

2023-08-16 15:28 UTC, andrutza requested changes

2023-08-16 15:28 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/service/CustomerServiceImplTest.java
> +    void addCustomer()
Can you please also add @DisplayName for each test method to say more explicitly what the method represents?

2023-08-16 15:28 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/service/CustomerServiceImplTest.java
> +    void addCustomer()
I recommend for each test method to begin with test (example: testAddCustomer()).

2023-08-16 15:28 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/service/CustomerServiceImplTest.java
> +        Customer alin = new Customer("Alin");
Can you please extract each hardcoded value to a constant?

2023-08-16 15:28 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/service/ProductServiceImplTest.java
> +        assertThrows(NonexistentProductException.class, () -> productService.getProduct(2L));
You should have a separate test for the scenario when the method throws an exception.

2023-08-16 15:30 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +            System.out.println("-------------List Products---------------");
I still don't see this change.

2023-08-17 14:34 UTC, andrutza requested changes

2023-08-17 14:34 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +                MainConsole.printMessage("Type \"Begin\" to start!");
Can you please just call in the main method another principal method from your MainConsole class and move all the logic there?

2023-08-17 14:34 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/service/CustomerServiceImplTest.java
> +    static final String name1 = "Alin";
You can just name the constant exactly what it represents: NAME_ALIN (don't forget about the convention).

2023-08-18 12:43 UTC, andrutza approved these changes

2023-08-19 10:12 UTC, merged