Ioan cosarca task 2
IoanCosarca/Bistro-Application pull request #3
Opened 2023-08-28 13:24 UTC by IoanCosarca

Request for merging the changes made in the second demo

2023-08-29 08:07 UTC, andrutza requested changes

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
> +                e.printStackTrace();
Please try to avoid e.printStackTrace().

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/BistroApplication.java
>      public static void main(String[] args)
Please keep the main method as simple as possible and move everything else to the console layer.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +    public static final String BASE_URL = "/api/customers";
Can you please move the base url /api to be defined as a generic url and also add the versioning of your api (this should be the first version v1, in the future probably will be other versions).

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +    public CustomerSetDTO getCustomers() {
Please also use the @Operation annotation to describe more clearly what the method does.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +    @PostMapping
Can you please also specify what each endpoint produces and consumes?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/CustomerController.java
> +        Validator validator = factory.getValidator();
I think it's easier to use the @Valid annotation instead of all this logic.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/OrderController.java
> +    public void saveOrder(PlacedOrderDTO order) {
What is the purpose of this method?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/ProductController.java
> +    public void deleteByID(@PathVariable Long id) {
You should use the java convention when defining the method's name.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/domain/IngredientType.java
> +    TOMATO_S("TOMATO SAUCE"),
Why have you modified this enum type?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/domain/PlacedOrder.java
> +package com.ntt.bistroapplication.domain;
It's better to have only one package for the all the model definitions (model/domain) that contain the dtos and the entities.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/exception/RestResponseEntityExceptionHandler.java
> +        StringBuilder bodyOfResponse = new StringBuilder();
You can define a generic exception response object to be used for all the exception handler methods.

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/model/CustomerSetDTO.java
> +public class CustomerSetDTO {
Does this need to be a separate dto class?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/CustomerServiceImpl.java
> +    @Autowired
Why do you need autowired here?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/CustomerServiceImpl.java
> +        this.customerMapper = CustomerMapper.INSTANCE;
Why do you need to use CustomerMapper.INSTANCE here?

2023-08-29 08:07 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/domain/Customer.java
> -    @OneToMany(mappedBy = "customer")
Where did the relationships disappear?

2023-08-29 08:56 UTC, IoanCosarca commented on src/main/java/com/ntt/bistroapplication/controller/OrderController.java
> +    public void saveOrder(PlacedOrderDTO order) {
The purpose is to save the orders I created in Main, so the table has something in it. Maybe as a future improvement it can be converted into an endpoint.

2023-08-29 09:19 UTC, IoanCosarca commented on src/main/java/com/ntt/bistroapplication/domain/Customer.java
> -    @OneToMany(mappedBy = "customer")
I experimented and observed that the table generation and relationship was not affected by removing it. And I never used that property. I can put the relationships back, if it is more recommended.

2023-08-29 12:19 UTC, IoanCosarca commented on src/main/java/com/ntt/bistroapplication/domain/IngredientType.java
> +    TOMATO_S("TOMATO SAUCE"),
The name was too long

2023-08-30 07:23 UTC, andrutza requested changes

2023-08-30 07:23 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/controller/OrderController.java
> +    @Operation(summary = "Retrieves the most ordered n products")
Please modify the text "n products" with number of products.

2023-08-30 07:23 UTC, andrutza commented on src/main/java/com/ntt/bistroapplication/service/CustomerService.java
> + * The service interface for the Customer Table.
You can just specify customer, without table.

2023-08-30 09:01 UTC, merged