Controller tests
IoanCosarca/Bistro-Application pull request #4
Opened 2023-09-08 09:22 UTC by IoanCosarca

Merge controller tests into the main branch

2023-09-20 13:06 UTC, andrutza requested changes

2023-09-20 13:06 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/controller/v1/CustomerControllerTest.java
> +class CustomerControllerTest {
For the controller-layer classes I recommend using @WebMvcTest.

2023-09-20 13:06 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/controller/v1/CustomerControllerTest.java
> +        Set<CustomerDTO> customers = new HashSet<>();
You can extract the setup part to separate method.

2023-09-20 13:06 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/controller/v1/OrderControllerTest.java
> +        mockMvc.perform(get(OrderController.BASE_URL + "/customerOrders/" + ID)
You can extract the path to a constant.

2023-09-20 13:06 UTC, andrutza commented on src/test/java/com/ntt/bistroapplication/controller/v1/ProductControllerTest.java
> +import static org.hamcrest.Matchers.*;
please try not to import everything from a certain reference, import only the resources that you need.

2023-09-24 06:57 UTC, IoanCosarca commented on src/test/java/com/ntt/bistroapplication/controller/v1/ProductControllerTest.java
> +import static org.hamcrest.Matchers.*;
Intellij auto-imported the resources from org.hamcrest.Matchers as I was writing the code and it considered that enough things were imported to put org.hamcrest.Matchers.*

2023-10-02 14:17 UTC, andrutza approved these changes

2023-10-02 20:06 UTC, merged